<a href="https://colab.research.google.com/github/KrzysztofLason/data-science-bootcamp/blob/master/Algebra_Liniowa.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Norma Wektora, długość wektora w R*2
w = [v1, v2]
Wektor ma początek i koniec i opisuje nam kierunek. Mamy dwie współrzędne
Norma wektora = pierwiastek z kwadratów sumy współrzędnych wektora.
Odgległość euklidesowa od środka układu współrzędnych = pierwiastek z v1*2 + v2*2

In [0]:
import numpy as np
np.__version__

'1.18.3'

In [0]:
v1 = np.array([0, 4])
v1

array([0, 4])

In [0]:
np.linalg.norm(v1) #linalg - moduł odnoszący się do algebry liniowej, norm - policzy nam normę wektora

4.0

In [0]:
vs =[-1, 4]
np.linalg.norm(vs)

4.123105625617661

In [0]:
v2 = np.array ([-10, 10, 13]) #przestrzeń R3
np.linalg.norm(v2)

19.209372712298546

# Odległość dwóch pkt. na płaszczyźnie

Suma kwadratów różnic pod pierwiastkiem
X (x1, x2)  Y(y1, y2)
Pierwiastek ((x1-y1)**2 + (x2-y2)**2)

In [6]:
p = np.array([3, 0])
q = np.array([0, 4])
# (Odleglosc miedzy p i q to norma wektora(p-q))
np.linalg.norm(p-q)

5.0

In [5]:
#Ręczne liczenie:
x = np.sqrt((3-0)**2+(0-4)**2)
x

5.0

In [7]:
a = np.array([3, 0, 1])  #tutaj jest wymiar R3
b = np.array ([0, 4, 2])
np.linalg.norm(a-b)

5.0990195135927845

# Mnożenie Macierzy
A - macierz wymiaru m x n
B - macierz wymiaru n x p
c - macierz wymiaru m x p

Aby móc pomnożyć dwie macierze liczba kolumn w lewej macierzy musi się zgadzać z liczbą wierwszy prawej macierzy. Mnożenie macierzy NIE jest przemienne.

In [9]:
X = np.array([[5,3], [3,9]]) #X to macierz 2X2 a Y macierz 2X1. Ich mnożenie da nam macierz 2 x 1. Mnozymy 5x
Y = np.array([[1], [-1]])
print(X)
print(Y)

[[5 3]
 [3 9]]
[[ 1]
 [-1]]


In [10]:
Z = np.dot(X, Y)
Z

array([[ 2],
       [-6]])

In [11]:
Z = np.dot(Y,X) #błąd bo wymiary się nie zgadzają! Mnożenie macierzy nieprzemienne.

ValueError: ignored

In [18]:
X1 = np.array([[5, 3, 3], [3, 5, 3], [3, 3, 2]])
print(X1, '\n')
Y1 = np.array ([[1, 1, 1], [2, 2, 2]])
print(Y1, '\n')
Z = np.dot(Y1,X1)
print(Z)

[[5 3 3]
 [3 5 3]
 [3 3 2]] 

[[1 1 1]
 [2 2 2]] 

[[11 11  8]
 [22 22 16]]



# Wyznacznik, Macierz jednostkowa, odwrotna i transponowana


In [21]:
#Wyznacznik macierzy  A = det A
# Liczenie poszcze
# A = [a11  a12
#      a21 a22 ]
# det A = a11a22 - a12a21 
# A = [ 2  2
#      10 12]
#det A = 24 - 20 = 4

A = np.array([[2, 4], [-1, 3]])
round(np.linalg.det(A))

10.0

In [23]:
#Ślad macierzy -> suma po przekątnej

A = np.array([[2, 4], [-1, 3]])
np.trace(A)

5

Macierz jednostkowa - macierz kwadratowa, której współczynniki podane są wzorem aij = 1 dla i =j, 0 dla i != j

np. I = [1], lub I = [1, 0]
                     [0, 1]
I = [1 0 0
     0 1 0
     0 0 1]
  

In [34]:
A = np.eye(3, dtype ='int')
B = np.eye(5, dtype ='float')
print(A,B)

[[1 0 0]
 [0 1 0]
 [0 0 1]] [[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [47]:
#Macierz odwrotna - A - macierz kwadratowa stopnia n. Macierz A posiada macierze odwrotną, gdy istnieje macierz B, taka, żę AB = BA = I
#Macierze inne niż kwadratowe, nie mają macierzy odwrotnych!!!
A = np.array([[2,4],[-1,3]])
print(A)
#Liczenie macierzy odwrotnej 
B = np.linalg.inv(A)
print(B)
#sprawdzenie - mnożąc AB dostaniemy macierz jednostkowa
np.set_printoptions(precision = 4, suppress = True)
C = np.dot(A,B)
print(C)

[[ 2  4]
 [-1  3]]
[[ 0.3 -0.4]
 [ 0.1  0.2]]
[[1. 0.]
 [0. 1.]]


In [57]:
#Macierz transponowana - Zamiana wierszy na kolumny
# Macierz 2x3 po transponowaniu jest 3x2
#Przykład w bibliotece Numpy:
A = np.array([[2,4],[-1,3]])
np.transpose(A)
#ALBO:
X = A.T
print(A, '\n')
print(X)

[[ 2  4]
 [-1  3]] 

[[ 2 -1]
 [ 4  3]]


# Rozwiązywanie układów równań



In [65]:
# możemy zapisać układ równań w formie macierzy współczynników (A), wektory wyrazów wolnych (B) i wektory niewiadomych. (X) GDZIE:
# AX = B
# A**-1 AX = A**-1B
# X = A**-1B

#Przykład
#UKŁAD MA POSTAĆ:  2x +4y = 10,  x-y = - 1
# Ręcznie to byłoby 

A = np.array([[2,4],[1,-1]])
B = np.array([10, -1])
A_inv = np.linalg.inv(A)
X = np.dot(A_inv, B)
X
#X to macierz z rozwiązaniam danego układu równań


array([1., 2.])

# Funckje Statystyczne w NumPy


In [66]:
import numpy as np
np.__version__

'1.18.3'

In [68]:
price = np.array ([[12.4, 12.8, 11.9, 12.6, 1000],
                   [12.5, 13.0, 11.7, 12.2, 2000],
                   [12.2, 13.4, 12.2, 13.2, 1500]])
print(price)

[[  12.4   12.8   11.9   12.6 1000. ]
 [  12.5   13.    11.7   12.2 2000. ]
 [  12.2   13.4   12.2   13.2 1500. ]]


In [69]:
price.sum() #suma wszystkich liczb w macierzy


4650.1

In [72]:
# po której osi liczymy
price.sum(axis = 0) #suma poszczególnych kolumn

array([  37.1,   39.2,   35.8,   38. , 4500. ])

In [71]:
price.sum(axis= 1) #suma poszczególnych wierszy

array([1049.7, 2049.4, 1551. ])

In [73]:
np.min(price) #minimum z całej tablicy

11.7

In [75]:
np.min(price, axis=0) #najmniejszy wiersz

array([  12.2,   12.8,   11.7,   12.2, 1000. ])

In [76]:
np.median(price
          )

12.6

In [78]:
np.mean(price, axis=0)

array([  12.3667,   13.0667,   11.9333,   12.6667, 1500.    ])

In [79]:
np.std(price, axis=0) #odchylenie standardowe poszczególnych kolumn

array([  0.1247,   0.2494,   0.2055,   0.411 , 408.2483])

In [81]:
np.var(price, axis=0) #wariancja poszczególnych kolumn

array([     0.0156,      0.0622,      0.0422,      0.1689, 166666.6667])