<a href="https://colab.research.google.com/github/KrzysztofLason/data-science-bootcamp/blob/master/Data_Science_Bootcamp.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

**1. Numpy-Tablice**


In [10]:
print('Hello Colab')

Hello Colab


In [9]:
import numpy as np
np.__version__


'1.18.1'

In [8]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import

In [0]:
help(np.array)

**Tablice jednowymiarowe**


In [7]:
x = np.array([1, 3])
print(x)

[1 3]


In [11]:
type(x)

numpy.ndarray

In [12]:
x.ndim #wymiar naszej tablicy

1

In [13]:
x.shape #kształt naszej tablicy - tupla (), bedzie 2 elementowa

(2,)

In [14]:
x.size 

2

In [15]:
x.dtype 

dtype('int64')

In [19]:
x = np.array([1.3,2.3,1.4])
print(x)

[1.3 2.3 1.4]


In [20]:
x.dtype

dtype('float64')

**Tablice dwu-wymiarowe**


In [23]:
x = np.array([[1, 2], [-3, 1]])
print(x)

[[ 1  2]
 [-3  1]]


In [24]:
x.ndim

2

In [25]:
x.shape

(2, 2)

In [29]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [30]:
x.shape #dwa wiersze, trzy kolumny

(2, 3)

In [32]:
x.ndim

2

**3D Array**


In [35]:
x = np.array([[[4, 3, 1],
              [3, 1, 2]],
             [[4, 1, 3],
              [4, 2, 1]]])
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [36]:
x.ndim

3

In [37]:
x.shape #2 tablice, 2wiersze, 3 kolumny

(2, 2, 3)

**2.Typy Danych w Numpy** # New Section

In [38]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [39]:
A = np.array([1.2, 1.1, 1.3])
A.dtype

dtype('float64')

In [41]:
A = np.array([1, 2, 3], dtype='float') #ustawienie parametru dtype na liczby zmiennoprzecinkowe
A.dtype

dtype('float64')

In [45]:
A = np.array([1, 2, 3], dtype='complex') #liczby złożone
A.dtype

dtype('complex128')

In [48]:
A = np.array([1.1, 2.4, 3], dtype='int')  #nastąpi transformacja danych do liczb całk. (np. 1.1 = 1)
A.dtype

dtype('int64')

In [49]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [53]:
A = np.array([24, 120, 230], dtype=np.int8)  #iczby całkowite 8bitowe np do tworzenia obrazów o mniejszym rozmiarze
A.dtype

dtype('int8')

In [56]:
A = np.array([24, 120, 230], dtype=np.uint8)  #unsite int - od 0 - 255
A.dtype

dtype('uint8')

**3. Tworzenie Tablic**  # New Section

In [59]:
np.zeros(shape=(4, 10), dtype ='int') #cztery wiersze i 10 kolumn, domyślny typ danych to float.

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [61]:
np.ones(shape=(5,5), dtype ='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [62]:
np.full(shape = (3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [64]:
np.arange(10) #bedzie to tablica dla danego range'a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [65]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [66]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [67]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [68]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [69]:
np.linspace(start=0, stop=1,num=10) #10 równomiernie rozłożonych elementów z danego przedziału.

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [0]:
A = np.arange(15)
B = np.arange(20)
print(A.reshape((3,5)))#iloczyn rozmiarów musi nam dawac 15 
print('Macierz B:')
B.reshape((4,5))

In [0]:
 A = np.arange(15)
 A.reshape((3,-1))  #automatyczne wykrywanie wymiaru = -1, chcemy miec 3 wiersze, a Python niech mi dobierze odpowiednia liczbe kolumna

