<a href="https://colab.research.google.com/github/KrzysztofLason/data-science-bootcamp/blob/master/Data_Science_Bootcamp/01.WprowadzenieNumPy/01.NumpyIntro.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tablice 1D, 2D i 3D Array w Numpy

In [0]:
print('Hello Colab')

Hello Colab


In [4]:
import numpy as np
np.__version__


'1.18.1'

In [0]:
print(dir(np))

['ALLOW_THREADS', 'AxisError', 'BUFSIZE', 'CLIP', 'ComplexWarning', 'DataSource', 'ERR_CALL', 'ERR_DEFAULT', 'ERR_IGNORE', 'ERR_LOG', 'ERR_PRINT', 'ERR_RAISE', 'ERR_WARN', 'FLOATING_POINT_SUPPORT', 'FPE_DIVIDEBYZERO', 'FPE_INVALID', 'FPE_OVERFLOW', 'FPE_UNDERFLOW', 'False_', 'Inf', 'Infinity', 'MAXDIMS', 'MAY_SHARE_BOUNDS', 'MAY_SHARE_EXACT', 'MachAr', 'ModuleDeprecationWarning', 'NAN', 'NINF', 'NZERO', 'NaN', 'PINF', 'PZERO', 'RAISE', 'RankWarning', 'SHIFT_DIVIDEBYZERO', 'SHIFT_INVALID', 'SHIFT_OVERFLOW', 'SHIFT_UNDERFLOW', 'ScalarType', 'Tester', 'TooHardError', 'True_', 'UFUNC_BUFSIZE_DEFAULT', 'UFUNC_PYVALS_NAME', 'VisibleDeprecationWarning', 'WRAP', '_NoValue', '_UFUNC_API', '__NUMPY_SETUP__', '__all__', '__builtins__', '__cached__', '__config__', '__doc__', '__file__', '__git_revision__', '__loader__', '__name__', '__package__', '__path__', '__spec__', '__version__', '_add_newdoc_ufunc', '_distributor_init', '_globals', '_mat', '_pytesttester', 'abs', 'absolute', 'absolute_import

In [0]:
help(np.array)

**Tablice jednowymiarowe**


In [0]:
x = np.array([1, 3])
print(x)

[1 3]


In [0]:
type(x)

numpy.ndarray

In [0]:
x.ndim #wymiar naszej tablicy

1

In [0]:
x.shape #kształt naszej tablicy - tupla (), bedzie 2 elementowa

(2,)

In [0]:
x.size 

2

In [0]:
x.dtype 

dtype('int64')

In [0]:
x = np.array([1.3,2.3,1.4])
print(x)

[1.3 2.3 1.4]


In [0]:
x.dtype

dtype('float64')

**Tablice dwu-wymiarowe**


In [0]:
x = np.array([[1, 2], [-3, 1]])
print(x)

[[ 1  2]
 [-3  1]]


In [0]:
x.ndim

2

In [0]:
x.shape

(2, 2)

In [0]:
x = np.array([[1, 2, 4], [4, 2, 1]])
print(x)

[[1 2 4]
 [4 2 1]]


In [0]:
x.shape #dwa wiersze, trzy kolumny

(2, 3)

In [0]:
x.ndim

2

**3D Array**


In [0]:
x = np.array([[[4, 3, 1],
              [3, 1, 2]],
             [[4, 1, 3],
              [4, 2, 1]]])
x

array([[[4, 3, 1],
        [3, 1, 2]],

       [[4, 1, 3],
        [4, 2, 1]]])

In [0]:
x.ndim

3

In [0]:
x.shape #2 tablice, 2wiersze, 3 kolumny

(2, 2, 3)

#Typy Danych w Numpy 



In [0]:
A = np.array([1,2,3])
A.dtype

dtype('int64')

In [0]:
A = np.array([1.2, 1.1, 1.3])
A.dtype

dtype('float64')

In [0]:
A = np.array([1, 2, 3], dtype='float') #ustawienie parametru dtype na liczby zmiennoprzecinkowe
A.dtype

dtype('float64')

In [0]:
A = np.array([1, 2, 3], dtype='complex') #liczby złożone
A.dtype

dtype('complex128')

In [0]:
A = np.array([1.1, 2.4, 3], dtype='int')  #nastąpi transformacja danych do liczb całk. (np. 1.1 = 1)
A.dtype

dtype('int64')

In [0]:
A = np.array([True, False])
A.dtype

dtype('bool')

In [0]:
A = np.array([24, 120, 230], dtype=np.int8)  #iczby całkowite 8bitowe np do tworzenia obrazów o mniejszym rozmiarze
A.dtype

dtype('int8')

In [0]:
A = np.array([24, 120, 230], dtype=np.uint8)  #unsite int - od 0 - 255
A.dtype

dtype('uint8')

# Tworzenie Tablic


In [0]:
np.zeros(shape=(4, 10), dtype ='int') #cztery wiersze i 10 kolumn, domyślny typ danych to float.

array([[0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0],
       [0, 0, 0, 0, 0, 0, 0, 0, 0, 0]])

In [0]:
np.ones(shape=(5,5), dtype ='int')

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [0]:
np.full(shape = (3,3), fill_value=4, dtype='int')

array([[4, 4, 4],
       [4, 4, 4],
       [4, 4, 4]])

In [0]:
np.arange(10) #bedzie to tablica dla danego range'a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [0]:
np.arange(start=5, stop=10)

array([5, 6, 7, 8, 9])

In [0]:
np.arange(start=10, stop=100, step=10)

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [0]:
np.arange(start=100, stop=10, step=-10)

array([100,  90,  80,  70,  60,  50,  40,  30,  20])

In [0]:
np.arange(start=0, stop=1, step=0.05)

array([0.  , 0.05, 0.1 , 0.15, 0.2 , 0.25, 0.3 , 0.35, 0.4 , 0.45, 0.5 ,
       0.55, 0.6 , 0.65, 0.7 , 0.75, 0.8 , 0.85, 0.9 , 0.95])

In [0]:
np.linspace(start=0, stop=1,num=10) #10 równomiernie rozłożonych elementów z danego przedziału.

array([0.        , 0.11111111, 0.22222222, 0.33333333, 0.44444444,
       0.55555556, 0.66666667, 0.77777778, 0.88888889, 1.        ])

In [0]:
A = np.arange(15)
B = np.arange(20)
print(A.reshape((3,5)))#iloczyn rozmiarów musi nam dawac 15 
print('Macierz B:')
B.reshape((4,5))

In [0]:
 A = np.arange(15)
 A.reshape((3,-1))  #automatyczne wykrywanie wymiaru = -1, chcemy miec 3 wiersze, a Python niech mi dobierze odpowiednia liczbe kolumna



# Podstawowe operacje na tablicach 


In [0]:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])

In [7]:
A + B #operacja wykonywana po elementach

array([6, 1, 7, 4])

In [8]:
A - B  #operacja wykonywana po elementach

array([0, 3, 1, 0])

In [9]:
A * B  #operacja wykonywana po elementach

array([ 9, -2, 12,  4])

In [11]:
A / B #nasza tablica przez którą dzielimy, nie może zawierać 0, zwraca na m liczbę typu float


array([ 1.        , -2.        ,  1.33333333,  1.        ])

In [17]:
A + 3 #dodawanie stałej - 3, do każdego elementu. Tak samo odejmowanie i mnożenie.

array([6, 4, 7, 5])

In [18]:
2 * A

array([6, 2, 8, 4])

In [19]:
A + 3*B

array([12, -2, 13,  8])

In [26]:
#Funkcje np do działania na tablicach:
A = np.array([3, 1, 4, 2])
B = np.array([3, -1, 3, 2])
x = np.add(A, B)
y = np.subtract(A, B)
z = np.multiply(A, B)
x1 = np.abs(B)
x2 = np.divide(A,B)
print(x, 
      y ,
      z,
      x1,
      x2)

[6 0 7 4] [0 2 1 0] [ 9 -1 12  4] [3 1 3 2] [ 1.         -1.          1.33333333  1.        ]


In [30]:
#Działania na Macierzach
X = np.array ([[1, 3], [-2,0]])
Y = np.array([[6,0], [-1,2]])
print(X, '\n')
print(Y)

[[ 1  3]
 [-2  0]] 

[[ 6  0]
 [-1  2]]


In [31]:
X * Y #mnoży nam element po elemencie!


array([[6, 0],
       [2, 0]])

In [32]:
np.dot(X,Y) #Mnożenie Macierzowe - (wiersz razy kolumna, wiersz zary kolumna.) MNOŻENIE MACIERZY NIE JEST PRZEMIENNE!

array([[  3,   6],
       [-12,   0]])

In [33]:
X @ Y #inny sposób.

array([[  3,   6],
       [-12,   0]])

In [35]:
X.dot(Y) #możemy urzyć na konkretnej macierzy metodę dot

array([[  3,   6],
       [-12,   0]])

# Generowanie liczb pseudolosowych - np.random

In [0]:
np.random.seed(0) #ziarno losowania - tak aby był stały wynik

In [43]:
np.random.randn()

1.764052345967664

In [44]:
np.random.randn(10, 4) #10 losowo wartość z rozkładu normalnego, odchylenie stand = 1,

array([[ 0.40015721,  0.97873798,  2.2408932 ,  1.86755799],
       [-0.97727788,  0.95008842, -0.15135721, -0.10321885],
       [ 0.4105985 ,  0.14404357,  1.45427351,  0.76103773],
       [ 0.12167502,  0.44386323,  0.33367433,  1.49407907],
       [-0.20515826,  0.3130677 , -0.85409574, -2.55298982],
       [ 0.6536186 ,  0.8644362 , -0.74216502,  2.26975462],
       [-1.45436567,  0.04575852, -0.18718385,  1.53277921],
       [ 1.46935877,  0.15494743,  0.37816252, -0.88778575],
       [-1.98079647, -0.34791215,  0.15634897,  1.23029068],
       [ 1.20237985, -0.38732682, -0.30230275, -1.04855297]])

In [45]:
np.random.rand()  #rozkład jednostajny na przedziale - zwróci nam liczbę losową z przediału 0-1

0.5701967704178796

In [47]:
np.random.rand(10, 2)

array([[0.43860151, 0.98837384],
       [0.10204481, 0.20887676],
       [0.16130952, 0.65310833],
       [0.2532916 , 0.46631077],
       [0.24442559, 0.15896958],
       [0.11037514, 0.65632959],
       [0.13818295, 0.19658236],
       [0.36872517, 0.82099323],
       [0.09710128, 0.83794491],
       [0.09609841, 0.97645947]])

In [48]:
np.random.randint(10) #Zwraca liczbę całkowitą <0;10)

2

In [49]:
np.random.randint(low=10, high=101) #zwraca losową liczbę dwucyfrową z przedziału (10, 101)

52

In [50]:
np.random.randint(low=10, high=101, size = 20)

array([87, 31, 83, 10, 20, 53, 68, 33, 69, 12, 72, 45, 77, 92, 56, 30, 91,
       60, 37, 24])

In [52]:
np.random.choice([4, 9, 1, 3, 5]) #zwraca losowy element z listy

1

In [53]:
np.random.choice(['python', 'java', 'sql'])

'java'

In [54]:
data = np.arange(10)
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [57]:
np.random.shuffle(data) #przetasuje nam dane, ta zmiana odrazu zachodzi na naszym obieckie w bibliotece NumPy, w Pandas trzebaby przypisać do zmiennej
data

array([3, 8, 9, 7, 4, 0, 5, 6, 2, 1])

# Podstawowe Funkcje w NumPy

In [58]:
np.exp(1) #zwraca nam stałą Eurela (e)

2.718281828459045

In [59]:
np.sqrt(25) #pierwiastek kwadratowy z 25

5.0

In [60]:
np.all([2, 3, 5, 6]) #zwraca wartość logiczną. Jeżeli każda = TRUE, łącznie będzie to prawda

True

In [61]:
np.all([2, 0, 5, 6]) #zwraca wartość logiczną. Jest False, bo 0 = False.

False

In [62]:
np.any([0, 0, 0, 1]) #szuka czy gdzieś jest chociaż 1 True

True

In [63]:
np.any([0, 0, 0, 0])

False

In [65]:
A = np.random.rand(5)  
A


array([0.89155444, 0.68005557, 0.44919774, 0.97857093, 0.11620191])

In [66]:
np.argmax(A) #zwróci nam indeks 3 bo ta wartość jest największa

3

In [67]:
A[np.argmax(A)]

0.978570928420717

In [68]:
A[np.argmin(A)] #wartość najniższa

0.1162019096123944

In [69]:
np.argsort(A) #Posortowane jest domyślnię rosnąco. Jest to użyteczne przy klasyfikacji wieloklasowej i chcemy mieć zwrócone np.
                # 3 najbardziej prawdopodobne klasy

array([4, 2, 1, 0, 3])

In [70]:
np.max(A) - wartość największa

0.978570928420717

In [71]:
np.min(A)

0.1162019096123944

In [72]:
np.mean(A) #średnia

0.6231161165881146

In [73]:
np.median(A) #mediana

0.6800555694634123

In [74]:
np.std(A) #odchylenie standardowe

0.3126848164219005

# Indeksowanie i wycinanie tablic

In [75]:
A = np.arange(20)
A

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [0]:
# Wycinanie podobnie jak w listach -  A[idx], A[start:stop], A[:stop] A[start:] A[-idx]

In [76]:
A[2]

2

In [77]:
A[2:]

array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17, 18,
       19])

In [78]:
A[:2]

array([0, 1])

In [79]:
A[[0,2]]

array([0, 2])

In [80]:
A[-1]

19

In [81]:
A[10:15]

array([10, 11, 12, 13, 14])

In [84]:
A = A.reshape(4,5) #przekształcanie
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [85]:
A [0] # cały pierwszy wiersz

array([0, 1, 2, 3, 4])

In [86]:
A [:,0] #cała pierwsza kolumna

array([ 0,  5, 10, 15])

In [88]:
A[:,-2]

array([ 3,  8, 13, 18])

In [90]:
A[1,1] #konkretny element wycięty - elemnt 6 (wierwsz 1 kolumna 1)

6

In [94]:
A[1:2, :2] #kilka elementów (wiersz 2, kolumna 1 i 2)

array([[5, 6]])

In [96]:
A[1,2] = 14 #przypisywanie nowych wartości w tablicy
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

# Iteracja po tablicach 

In [97]:
A

array([[ 0,  1,  2,  3,  4],
       [ 5,  6, 14,  8,  9],
       [10, 11, 12, 13, 14],
       [15, 16, 17, 18, 19]])

In [98]:
for row in A:
  print(row)

[0 1 2 3 4]
[ 5  6 14  8  9]
[10 11 12 13 14]
[15 16 17 18 19]


In [99]:
for row in A:  #indeks 0 z każdego wiersza
  print(row[0])

0
5
10
15


In [100]:
for item in A.flat:   #wypłaszczenie tablicy, żeby iterować element po elemencie
    print(item)

0
1
2
3
4
5
6
14
8
9
10
11
12
13
14
15
16
17
18
19


In [101]:
A.shape

(4, 5)

In [102]:
A.reshape(5,4)

array([[ 0,  1,  2,  3],
       [ 4,  5,  6, 14],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

In [103]:
A.ravel() #operacja zwrotna do reshape aby wrócić z powrtoem do płaskiej postaci jednowymiarowej

array([ 0,  1,  2,  3,  4,  5,  6, 14,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [104]:
A.transpose() #transponowanie macierzy (kolumy -> wiersze, wiersze -> kolumny )

array([[ 0,  5, 10, 15],
       [ 1,  6, 11, 16],
       [ 2, 14, 12, 17],
       [ 3,  8, 13, 18],
       [ 4,  9, 14, 19]])

# Maski Logiczne


In [114]:
A = np.arange(start=-10, stop=10, step=0.5)
A = A.reshape(10,-1) #zwróci nam 10x4 bo jest 40 elementów.
A

array([[-10. ,  -9.5,  -9. ,  -8.5],
       [ -8. ,  -7.5,  -7. ,  -6.5],
       [ -6. ,  -5.5,  -5. ,  -4.5],
       [ -4. ,  -3.5,  -3. ,  -2.5],
       [ -2. ,  -1.5,  -1. ,  -0.5],
       [  0. ,   0.5,   1. ,   1.5],
       [  2. ,   2.5,   3. ,   3.5],
       [  4. ,   4.5,   5. ,   5.5],
       [  6. ,   6.5,   7. ,   7.5],
       [  8. ,   8.5,   9. ,   9.5]])

In [115]:
A > 0 #False będzie wszędzie tam gdzie element <0, True przeciwnie.

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])

In [116]:
A[A>0] # możemy wycinać tak, że dostaniemy tylko elementy dotanie ()

array([0.5, 1. , 1.5, 2. , 2.5, 3. , 3.5, 4. , 4.5, 5. , 5.5, 6. , 6.5,
       7. , 7.5, 8. , 8.5, 9. , 9.5])

In [117]:
np.bitwise_and(A > -5, A < 5) #zwróci nam konkretną maskę, tam gdzie oba warunki są spełnione

array([[False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False]])

In [118]:
A[np.bitwise_and(A > -5, A < 5)]

array([-4.5, -4. , -3.5, -3. , -2.5, -2. , -1.5, -1. , -0.5,  0. ,  0.5,
        1. ,  1.5,  2. ,  2.5,  3. ,  3.5,  4. ,  4.5])

In [119]:
np.bitwise_or(A < -5, A > 5)

array([[ True,  True,  True,  True],
       [ True,  True,  True,  True],
       [ True,  True, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False, False],
       [False, False, False,  True],
       [ True,  True,  True,  True],
       [ True,  True,  True,  True]])